### ISSUE TITLE
在法律的框架下行动，成为自由软件运动的精神继承者，我们会获得最广泛的舆论支持

### ISSUE THREAD

**Issue by ff4415** [kattgu7/Anti-996-License#12]
我们的行为，不是为了超越法律， 而是为了不让法律蒙尘。

**Comment by ff4415** [comment]
Those actions, are not willing beyond laws,  but sharp it.

**Comment by firedom** [comment]
Great, let's keep up. 

我正在遍历996.ICU Pull request中的讨论，其中有一些有趣的观点，可以试图反推产生原因。

**Comment by Naville** [comment]
你们想搞蠢点子无所谓，球球里们不要跟个中二病犯了的傻逼一样到处spam你们的点子。
华裔在国外已经备受歧视了球球里们带点脑子不要再丢人现眼了。

**Comment by Naville** [comment]
承认自己无能，是可被替代的技术工种并想办法摆脱这个处境。而不是跟个睿智一样到处丢人现眼在毫无关系的国外项目里spam你们的没有人关心的点子。这样对大家都好

**Comment by ff4415** [comment]
@Naville  
人不中二枉少年。 兄弟。
生命就应该浪费在美好的事物上面。 不是？
人费曼不也说过了吗： 『What Do You Care What Other People Think?』。
just do it.

**Comment by ohhhhyaa** [comment]
> @Naville
> 人不中二枉少年。 兄弟。
> 生命就应该浪费在美好的事物上面。 不是？
> 人费曼不也说过了吗： 『What Do You Care What Other People Think?』。
> just do it.

加油

**Comment by specialsheep** [comment]
加油
