### ISSUE TITLE
Anti-996->改变程序员工作方式 （游戏、新的代码托管等等）

### ISSUE THREAD

**Issue by wellmoonloft** [kattgu7/Anti-996-License#14]
1、 由Anti-996-License团队作为盟主，成立松散的中国反996基金会组织
2、引导处于水深火热的全国程序员群策群力，通过Anti-996-License
3、由反996基金会组织成立实体法人公司，代表在开源许可证管辖内的开源项目向996公司追讨授权费
4、优化法人公司组织架构，成立“特别董事会”，许可证内项目的作者为董事会成员参与决策权
5、依托法人公司基金创建代码托管-在线打包及编译-在线部署-项目展示的平台为开源作者争取变现的方法。使用颗粒度到功能的微服务框架，比如系统登陆、用户添加，功能评价参考appstore。
* 最终实现流程如下：
公司A需要一套会员管理系统，该公司的IT登陆这个平台：
- 选择权限管理->进入权限管理服务列表->进入star最高的某个服务-
- 选择用户管理->进入用户管理服务列表->列表中会自动过滤适配了权限管理的所有的用户管理服务
...
类似早期的中关村在线装机，最终点击提交，后台自动拼凑所有服务代码，打包生成项目，用户获得15天试用权限，测试满意后直接付款。
支付的款项按某种比例反馈给各个代码作者。

**Comment by wellmoonloft** [comment]
与其给某个公司打工，不如加入组织给自己打工。
如果遇到某个项目需要封闭开发，可像当年乔老爷子研发mac一样，由项目发起人在组织内选择有共同志向的精英走向线下。
项目完毕后小组就可以解散回家。
这就是未来程序员的生活方式。

**Comment by wellmoonloft** [comment]
技术的问题用技术来解决
市场的问题用市场来解决
这个项目代表了很多程序员的心声，但同时对于zf来讲，每天都在刺探着他们的底线，如果因为某些言论或者行为造成了，哪怕特别小的社会危害，那么诸如南山必胜客之类一定会抓住机会按死在沙滩上
所以说各位英雄们还是要正确引导大家的思维，回到理性的途径来解决这个问题
我想，通过标准的法律途径，再加上全员创业，增加政府收入，积极向上，是最稳妥也是共生共赢的一个方式了。

**Comment by firedom** [comment]
可以成立基金会，但是这种组织结构目前看来过于庞大很难一步搞成。我认为可以先从做一个游戏开始获得收入[1]，然后将收入的一部分用于做一个信息整合网站[2]，帮助讨论者更快找到新的讨论方向。因为现在的一些讨论观点与过去的重复了，虽然参与的人很多但是获得的价值有限。

[1] https://github.com/lxlxw/996.TSC/issues/31    **996模拟器**
[2] https://github.com/lxlxw/996.TSC/issues/28#issuecomment-478949866

**Comment by firedom** [comment]
@wellmoonloft 如果通过成立基金会的形式制作一个与996有关的游戏，并在这个游戏中加入Anti-996-License。需要怎样做才会让这个过程具有可行性？

**Comment by wellmoonloft** [comment]
> @wellmoonloft 如果通过成立基金会的形式制作一个与996有关的游戏，并在这个游戏中加入Anti-996-License。需要怎样做才会让这个过程具有可行性？

我认为做一个游戏出来一定会比搭一套平台出来难度要相对小一点，但是有一个问题需要思考。
1. 因为996项目的热度，这个游戏也许会有知名度，但是否会成功？
2.这个游戏的实际意义是什么？

这就引申出一个问题，即便游戏成功，获取到了相关的关注度，然后呢？它的价值仍然围绕在反996这个概念的传播，但无法给予程序员们后续的希望并满足程序员们的诉求。

也许会有新的问题出现：
比如真的有公司同意恢复955，但是相对工资减少30%～50%
比如会有程序员愿意接受996来获取更有竞争力的岗位，而坚持不接受996的程序员会下岗
比如...

因此，真正反996组织需要做的事情的原则需要清晰
1. 尽量保障大部分程序员的权益不受损失
2.通过成立组织有规模的“虚拟组织”让程序员们有归属感，也就是所谓的带头大哥
3.需要尽快建立精神图腾，也就是说，我们到底是为了什么反996，再多思考一点就是
- 古代帝王用儒家思想控制人心，我们活着，要忠君爱国，报效祖国
- 种花家的早期居民为了中华民族的复兴和崛起
- 那么我们，为了什么而写代码？这个题很土，也很大，但是如果有这样的精神图腾出来，你懂的，信仰这种东西是不会冷却的。

针对第三点还可以解释，比如某为公司高层站出来问，好，你们的问题我知道了，我现在要帮你们解决，你说，你想怎么样？
谁能站出来回答这个问题？

这一点想不清楚，空喊口号到最后是不会得到任何解决的，因此搭建能让程序员活下去、活得体面、赚的开心的平台实际上可能确实是一条路。

人人都想SOHO，其实程序员也许是各种工种中最容易实现的那一种

**Comment by bofeiw** [comment]
如果做一款有关996的游戏，目的是向大众宣传996吗？如果是的话，就可能是非营利性的吧。如果目的是通过做游戏获得收入，那就不局限在996这个话题了。盈利的话需要加入道具广告等等，一款宣传性的游戏能加入这些东西吗？

最近看到了一个游戏：[THE EVOLUTION OF TRUST](https://ncase.me/trust/)，这个游戏通过互动讲述了一个博弈论这个概念，996游戏是不是可能借鉴这个游戏，通过互动来讲述996这个概念？

**Comment by wellmoonloft** [comment]
借用游戏这个话题再回答我上面提出的第三个问题，我们为什么要反996？我们为什么要写代码？我们最初踏入程序员这个行列到底为了什么？
我想起之前写过的一篇文章

<img width="650" alt="image" src="https://user-images.githubusercontent.com/20944693/55417520-6c820000-55a3-11e9-9126-b27933ae7a73.png">

写代码就是那样神奇而幸福的事情，对乔老爷子来讲，那一群有着偏执狂而又怪异的“怪人”，拥有着改变世界的能力，大多数比较好的程序员其实是不善于言辞和表达的，但是他们谈到自己的代码和成果眼睛里面是会散发光芒的。

我相信有很大一批人写代码是为了生存，但的确还是有更大一批人坚持着，相信自己能够通过代码来做一些“不一样”的事情。

所以其实上面我提出了问题之后，我一边在苦逼绕着循环，一边在思考我为什么要做程序员，于是我就想起了我之前写这篇文章的心情。

因此我仍然认为，反996最好的结果，并不是反996这个行为本身，而是能够借助这个事件，建立起由全体程序员共同营造的，一个保护自己权益的组织，这个组织公平、公正、公开，且有能力为大家争取应得的权益，协助或者代理程序员劳动成果变现，让更多的不善言辞、不爱社交的“死宅”们，可以幸福的继续写代码。

**Comment by bofeiw** [comment]
和朋友谈了谈996游戏，谈一下看法

盈利和宣传似乎是相互矛盾的。如果以宣传996这个概念为主要目的的话，就可能要暂时放下盈利，以非营利的方式召集一些有闲的开发者来开发这样一个游戏，当然如果游戏做的足够好的话，盈利也是有可能的。这里面是有一个主次关系的，主要宣传的话，盈利就需要先放在一边。如果主要为了筹集资金的话，就没必要通过996这个话题了，因为为了盈利做出来的游戏质量不会太高，会影响宣传的效果。我个人认为宣传比较重要。

游戏本质一定要好玩，不然别人连游戏都不愿意碰。好的游戏是靠宣传和口碑来积累玩家的，而第一批用户非常重要。现在996是个热点话题，如果做了一个996游戏，可能会有很多玩家，但是不代表这些玩家喜欢这个游戏，也不代表这个游戏的口碑会因玩家数量而上升。要积累口碑，并达到宣传效果，一定要把游戏做的好玩。

下面是朋友提供的一个思路

> 因为你要反映996存在问题，我举个大概情况，玩家扮演一个刚毕业的大学生，一开始有两份工，一份xx工资 早九晚五，一份更高工资 但是996作息，同时玩家有着日常支出，和自身健康情况，996会减少自身健康值，健康值下降会导致工作完成几率的下降，当健康值下降的一定程度时，会生病，生病会误工 花钱，通过正负面反馈，让玩家在选择中自我意识到996的弊端

**Comment by kattgu7** [comment]
@bofeiw @wellmoonloft @firedom hi, 各位，今天我和Suji咨询了一下专业人士的意见，暂时不方便设立基金会，实施起来比较困难。但是游戏的点子我觉得很好！我们需不需要开个issue专门讨论这个？

**Comment by wellmoonloft** [comment]
游戏的点子是@firedom最先提出的，由他去开一个新的issue比较好
我会在上班后追加我的思路，其实最重要解决的问题仍然是上面描述的，游戏实现会简单，但它的价值在哪里？我思考分三个等级：
1. 持续炒热996这个事情，持续拉关注
2.尝试通过团队协作，实现盈利
3.描绘一种未来可能的生存方式
价值体现是从低到高的，我们要做的不只是游戏本身，而是通过做游戏，来描绘一个完整的，从立项到变现的全流程解决方案（）。
一方面供其他人参考，同时也算是做一个正能量的引导。

**Comment by wellmoonloft** [comment]
这是我整理的思维导图，供各位参考。

<img width="1347" alt="anti-996" src="https://user-images.githubusercontent.com/20944693/55442618-0072bc80-55e2-11e9-8488-ac1746e9f0b3.png">

**Comment by SkyAndGround** [comment]
程序员不会画画/

**Comment by firedom** [comment]
一些公司会在签订劳动合同之前问员工一些列问题比如：
- 我们这个公司有时会突然多许多业务，有可能需要员工自愿待岗。请问你能接受么？
- 我们可能会给你安排一些很复杂的工作，虽然不要求你加班，但是如果做不完的话需要你加班做完。请问你能接受么？
- 公司有可能白天没有事可以做，但是晚上可能会很忙，这种情况我们算是把白天的工作时间移到晚上。请问你能接受么？

如果将这个过程看成分支选项，那么游戏会根据玩家选择得到不同的结局。（不必将游戏模式局限于此）

另外我新建了一个996游戏的repository，不过目前我不确定这个项目是否可行。所以先进行可行性讨论，然后决定下一步应该怎么做比较好。

https://github.com/firedom/996.GAME
对于开发过程可以考虑这么做：
- 因为反对996制度而被裁员的人可以加入进来制作这个游戏；
- 制作游戏的工具首先考虑使用添加了Anti996许可证工具/项目；
- 将发售游戏的收入按一定规则分配给参与制作的人/项目管理者；（如果可能）
- 在游戏制作过程中所有参与者都必须遵循Anti996许可证的约束（珍惜生命，远离ICU）。

这里我给一些issues发了一些建议：
https://github.com/lxlxw/996.TSC/issues/41
https://github.com/lxlxw/996.TSC/issues/36

**Comment by wellmoonloft** [comment]
关于游戏情节我有一个灵感，已在您的[仓库issue](https://github.com/firedom/996.GAME/issues/1#issue-428744865)

**Comment by specialsheep** [comment]
有点合作社的意味?(逃)

**Comment by ohhhhyaa** [comment]
资瓷资瓷

**Comment by specialsheep** [comment]
> 程序员不会画画

我似乎认识一些画师是程序员出身
ps 程序员出身的曲师似乎不少

**Comment by wellmoonloft** [comment]
> > 程序员不会画画
> 
> 我似乎认识一些画师是程序员出身
> ps 程序员出身的曲师似乎不少

越来越多的程序员被逼的学会了PS、AI、手绘、MIDI制作等等等等等等....

**Comment by yisiliu** [comment]
感觉是时候成立全国程序员工会了。。

**Comment by rpfbl** [comment]
[有人提议](https://t.me/anti996/12728)，[通过表情包来扩大宣传](https://t.me/anti996/12734)。
制作表情包门槛低，成本也低。

**Comment by kattgu7** [comment]
可以不可以把游戏做成一个普法的游戏？比如说，如果是通过不同分支选项有不同结局的，错误的选择后面跟上相关的劳动法条等。

**Comment by wellmoonloft** [comment]
> 可以不可以把游戏做成一个普法的游戏？比如说，如果是通过不同分支选项有不同结局的，错误的选择后面跟上相关的劳动法条等。

是一个很好的主意，但有点担心，[我在这里](https://github.com/firedom/996.GAME/issues/1#issuecomment-479525226l)已经写了一些选项和解决，但是为了故事性其实很多解决并不是那么的“正能量”，如果加入法律条款，就要修改故事让它看上去不是那么的“突兀”

单纯普法的游戏会担心过于教条而没人愿意去玩，不过明天我会试一试

**Comment by FredericMao** [comment]
对不起，我需要给游戏的提议泼一些凉水，先说抱歉。
1）有多少非程序员会对“模拟程序员人生“有兴趣？
    游戏的作用是什么？是“扩大”宣传。是把那些没有通过（网络和电视）媒体关注到996问题的人，引起他们的关注。游戏的受众人群很明显是小于媒体的。有多少人没有通过媒体，却通过游戏关注呢？anti996需要的是什么呢？只是关注吗？
2）程序员需要警惕从”自嘲“到”刻板印象“的转化
    大概是10年前，我和大学室友讨论了一个问题，我当时十分不解为什么网上会有大量的关于程序员的吐槽。我当时的观点是“无良黑心网络媒体”为了搏眼球故意编造（或者刻意扩大化）的故事。我的室友提出了一个思路，他说，这些负面内容很多出自于程序员的“自嘲”，其实大家就是想搞笑并吐槽一下人生罢了。通过自己的幽默给其他人带来欢乐，这是很好的一件事啊。但是，后果是什么呢？这些大量被媒体炒作的“自嘲”变成了社会对程序员的刻板印象。如果程序员对这些刻板印象无动于衷，反而是去迎合，觉得大概就是这样，慢慢的社会上就有更多人会加深这个刻板印象，甚至认为你们程序员自己都承认了。这个游戏的构思从某种意义上，是在加深社会对程序员的刻板印象，并不有助于改善程序员在社会中的角色。
3）接受并仔细考虑其他人的逻辑
   你知道我第一眼看到这个”做游戏“的提议，我想的是什么吗？我想：” 呵呵，这帮程序员，遇到问题不去想怎么解决，”又“把问题转换成自己的兴趣，然后沉迷在自己意淫的世界不能自拔了。“ 请你们先不要反驳我的观点。先想一想，这个逻辑有没有道理？再想一想，就算这个逻辑毫无道理，这重要吗？这就是我的想法，就算是错的又怎么样？在我眼里的很多程序员就是这样的。我认为做游戏并不有助于帮助解决996的问题，反而会加深社会对程序员群体的刻板印象。
4）anti996是反对无良企业，并不是反对刻板印象
   看到这里，我想很多人有了这个想法，“你说了这么多刻板印象，我都知道啊，这对anti996有什么帮助呢？” 现代私有企业是职能是“服务股东”，也就是给股东创造更大的利益。压榨（或者说的难听一点”非人道“对待）程序员，真的能给企业赚更多的钱吗？我想这个问题的答案是不唯一的。如果答案是”是“，那么这个违法行为的动机就很明确了，就是贪婪。但我想，很多时候这个答案应该是”不知道，可能有吧“。公司规章的制定者，为什么”知法犯法“，厚颜无耻到如此境地？难度不是因为看到了程序员的某些”特质“？比如”活在自己幻想的次元“，对现实社会的变革”不感兴趣“，只”沉迷技术“，”不善社交“，”不善与广大群众交往“。我们必须看到的是，即便是IT公司的管理人员，他们对程序员的看法很多事建立在这样那样的“刻板印象”之上的。不仅仅是管理层，就是下面的一些负责人员甚至小员工，都对程序员这个群体有着极大的误解与偏见。比方说，公司年会为什么要请av女优？为什么公司活动策划和拍板的人觉得av女优的出场是一种好的活动？难道不是因为他们觉得“程序员都是宅男”，“没有性生活”，“女朋友在硬盘”上，”如果把硬盘上的人搞到现实里，程序员一定会立刻高潮“吗？
5）我不反对对游戏制作有兴趣的人从事到这个项目里。如果你们想做就去做，自我很好。大家集思广益，贡献各自的力量是个很好的事。我周六一大早起来 （UTC-4：00），饭都没吃，就写了这么多字，只是希望大家能够把更多的力量放到更重要的地方。
6）路人甲对我说：“说了这么多屁话，你说咋办吧”
    我不想去说什么“法国大革命”，也不想说什么”非暴力不合作“，这些东西。那些东西都很复杂，而anti996应该是很单纯的。（这点很重要，保持996的单纯性，是一切的前提条件，一定要谨防那些想动歪脑筋的人！）我理解的anti996的夙愿是：互联网公司停止对员工的压榨，停止违法的加班制度，对员工有更多的人文关怀。最后这一点我认为最重要，为什么这些公司可以这样肆无忌惮，不仅仅是因为他们有钱有关系，而且是因为公司的管理层和其他员工，只是把程序员当”程序猿“看罢了。猴子在人类社会的角色是什么呢？耍猴，给人乐子，如果还能搬砖，岂不美哉？
7）有人肯定要问，你什么背景，凭什么大言不惭地对程序员指指点点？我做什么的不重要，你们当我是个键盘侠就好了。抱歉，献丑了。

**Comment by wellmoonloft** [comment]
关于您的提议，我有自己的一些思考，其实跟您的思路也有类似的地方，参考了996.LEAVE我写出了不同的一个思路，[放到了这里](https://github.com/wellmoonloft/996.WORLD)，您可以给一些意见。

> 对不起，我需要给游戏的提议泼一些凉水，先说抱歉。
> 1）有多少非程序员会对“模拟程序员人生“有兴趣？

**Comment by Tedko** [comment]
hi请移步 #33 讨论
