### ISSUE TITLE
现有协议缺乏威慑性，且可执行性不足，无法提供牵制的力量

### ISSUE THREAD

**Issue by x007007007** [kattgu7/Anti-996-License#16]
提供一个我的设想

【关于复制、分发和修改的术语和条件】

〇、定义

　　“本扩展协议”指反996文化强制开源源码协议v1。
　　“版权”也指适用于诸如半导体掩模的其他类型作品的类似法律。
　　“本程序”指任何在本扩展协议保护下的有版权的作品。每个许可获得者称作“你”。“许可获得者”和“接收者”可以是个人或组织。
　　“修改”一个作品指需要版权许可的复制及对作品全面的或部分的改编行为，有别于制作副本。所产生的作品称作前作的“修改版”，或“基于”前作的作品。
　　“受保护作品”指程序或其派生作品。
　　“传播”作品指那些未经许可就会在适用版权法律下构成直接或间接侵权的行为，不包括在计算机上运行和私下的修改。传播包括复制、分发（无论修改与否）、向公众公开，以及在某些国家的其他行为。
　　“转发”作品指让他方能够制作或者接收副本的行为。仅仅通过计算机网络和用户交互，没有传输副本，则不算转发。
    "开发人员"是指当许可获得者为组织时，所有参与修改本程序源码的人与所有使用过"修改版"的人
    "工作"是指利劳动者在同一组织，通过用劳动换取报酬的行为。
    "健康工作时长"是指一个人24小时内累计工作时长不超过8小时，或一个人168小时内累计工作总时长不超过40小时。
    "超过健康工作时长"是指一个人24小时内累计工作时长超过8小时，或者一个人168小时内累计工作总时长超过40小时。
    "过劳开发人员"是指任意一名开发人员工作"超过健康工作时长"

一、源码

　　作品的源码指其可修改的首选形式，目标码指所有其他形式。
　　“标准接口”指标准化组织定义的官方标准中的接口，或针为某种编程语言设定的接口中为开发者广泛使用的接口。
　　可执行作品中的“系统库”不是指整个程序，而是涵盖此等内容：(a)以通常形式和主部件打包到一起却并非后者一部分，且(b)仅为和主部件一起使作品可用或实现某些已有公开实现源码的接口。“主部件”在这里指可执行作品运行依赖的操作系统（如果存在）的必要部件（内核、窗口系统等），生成该作品的编译器，或运行所需的目标码解释器。
　　目标码形式的作品中“相应的源码”指所有修改作品及生成、安装、运行（对可执行作品而言）目标码所需的源码，包括控制上述行为的脚本。可是，其中不包括系统库、通用工具、未修改直接用于支持上述行为却不是该作品一部分的通常可得的自由软件。例如，相应的源码包含配合作品源文件的接口定义，以及共享库和作品专门依赖的动态链接子程序的源码。这里的依赖体现为频密的数据交换或者该子程序和作品其他部分的控制流切换。
　　相应的源码不必包含那些用户可以通过源码其他部分自动生成的内容。
　　源码形式作品的相应源码即其本身。

二、被授权人义务:

    1. 在本程序,本程序修改版以及所有副本中都必须包含本扩展协议。
    2. 当授权人为组织时
       a) 授权人有义务告知"开发人员"关于本附加协议的一切信息
       b) 如果"过劳开发人员"被组织要求参与本程序或本程序修改版特定版本的修改、传播、转发或运行，那么授权人有义务公开该版本的源码。并承担相应的法律风险。
       c) 如果"过劳开发人员"被组织要求参与本程序或本程序修改版特定版本的修改、传播、转发或运行，自动视为授权"本程序"以及"本程序公开衍生版"中使用该组织所有的专利。
       d）如果"过劳开发人员"被组织要求参与本程序或本程序修改版特定版本的修改、传播、转发或运行，履行义务将不受任何签署保密协议限制

三、开发人员义务：
    1. 当被授权人超过24小时未能履行义务时，雇佣者有义务代替授权人执行 被授权人义务中的 2.b 条款。为此产生的所有行为均属于正当，不应追究其责任。

**Comment by Tedko** [comment]
关于协议的修改已在咨询专业的律师。

**Comment by kattgu7** [comment]
@x007007007 Hi, I have given you feedback in slack, pls check. Thanks!
