### ISSUE TITLE
分享一个想法，有可能是个多赢的方案，而且可以得到企业政府的主动配合，希望大家可以探讨一下

### ISSUE THREAD

**Issue by lucaisacoder** [kattgu7/Anti-996-License#19]
我也有个想法和大家分享，这么久以来我们把996公司当做对立面，其实企业管理者想法也大多是高效益比，我们可以选择与企业对抗，也可以选择合作，积极帮助企业改善管理水平。
我觉得合作共赢的路子是各方都乐见的，可能是条真正可行的方式，希望大家可以深入探讨一下。

**Comment by Tedko** [comment]
谢谢建议！🙏🙏

**Comment by Tedko** [comment]
#12 在这讨论吧，Thanks
