### ISSUE TITLE
关于应对996工作制的本质法律原因和应对策略

### ISSUE THREAD

**Issue by CPdogson** [kattgu7/Anti-996-License#20]
**一、996工作制度的违法本质**
1、996工作制度本质是超法定加班
《劳动法》四十一条规定用人单位由于生产经营需要，经与工会和劳动者协商后可以延长工作时间，一般每日不得超过一小时;因特殊原因需要延长工作时间的，在保障劳动者身体健康的条件下延长工作时间每日不得超过三小时，但是每月不得超过三十六小时。
而996工作制度每日加班4小时，每月月72小时，远远的超过了法定的加班时间。也就是说：即使给够了钱，996工作制也是违反劳动法的。
2、双休制、8小时工作制、36小时加班制的起因与猜测
虽然我国属于社会主义国家，但是对劳动者有利的劳动法是1995年，中国从1985年开始复关WTO，直至2001年加入，虽然没有直接证据表明中国的8小时工作制和双休制和加入WTO有直接原因，但根据60年代后国人每周工作48小时，且无带薪休假权利，刘少奇等中央领导搞不赢资本主义，为什么还一定要坚持八小时工作？的言论，不难间接推断出中国劳动者工作时间制度和加入WTO要求脱不开关系。并且996工作制完全可以归纳为不正当竞争的范畴。
而我国明文记载的双休制和8小时工作制起因，最初的提出者则是时任国家科委中国科学技术促进发展研究中心主任的胡平，通过数十年的研究，经过邓小平的指示通过的。
3、应对策略概述
综上所述，消除996工作制有三个可以尝试的路径：法律途径、跨境贸易压力、侮辱先烈。
**二、法律途径**
1、推动劳动法完善
对《劳动法》的执法不严，违法不究，撇开中国本身希望扩大贫富差距，增加民众压力从而加快社会经济发展不谈。《劳动法》的缺陷在于：劳动法本质还是合同法，所以导致了申请诉讼、仲裁者只能是劳动者也就是当事人本人，在中国目前的环境下，对公司进行仲裁和诉讼之后，基本没有可能继续在公司里做下去。因此，让《劳动法》的原告范围增大，使竞争对手、公益组织可以成为诉公司违反劳动法的原告，是完善劳动法的一大途径。
**三、境外股市与贸易压力**
在列表中提到的部分违法企业（如华为）产品销售至人权较发达的欧美国家，亦有企业在香港和美国（如阿里巴巴）上市。本项目将通过海外宣传的手段，希望海外国家不要购买中国996工作制度下生产的产品，抛售对应公司的股票，拟给违反劳动法的大企业照成压力。
**四、宣传破坏双休及八小时工作制侮辱先烈**
《中华人民共和国英雄烈士保护法》是中国为限制网络言论出台的一部兜底法律，法律中规定英雄烈士家属可以通过起诉侮辱英雄烈士的单位或者个人。在2.2的政治背景中已经介绍八小时工作制的来历与中国英雄烈士有一定关联。而双休制和八小时工作制亦是中国共产党口中的无产阶级鲜血换来的制度。如果将八小时工作制和双休制与英雄烈士挂钩，便可依据《英烈保护法》对企业进行诉讼。
**五、意识推广**
1、明确996是违法现象
上文1.1已经说到，996的工作制远超每月36小时的加班限制，所以996无论给没给够钱，都是违法的。
针对很大一部分“给够钱什么都好说”的说法，首先是把“劳动者对休息权的争取”往“劳动者对利益的争取”方向带节奏。是对反996机制的一种抹黑。
其次劳动者自身要清楚，默许996实质上是一种恶意竞争行为，只要有一部分“工贼”认为996合理，那么资本家“你不干自然有人干”的想法就会产生，最终打压不愿意996的群体。——结果就是全员996，而且全员工资都“给不够”。
即使是类如腾讯“5:30下班、6:30晚饭、7:30免费班车、9点以后打车免费”的做法，实质上是对守时下班者的不公平对待，打着自愿的幌子强迫加班。根据自然法的观点，依然是违法现象。
2、明确反996目标，消除道德瑕疵
随着996icu的不断壮大，包括对策略(三)的实施，都可能导致，并且我们也希望境外媒体参与到中国反996的行动队伍中来，这样不免会有人把996icu和境外势力挂钩，进行抹黑。这时成员必将进行内斗，一部分认为996icu的确是境外势力的阴谋，将之与国家挂钩。
所以我们需要明确，996icu一切行动都是为了恢复到八小时工作制和双休制而努力，无论采用何种手段，只要不影响到国家主权问题，就是爱国的表现。受着996压迫的劳动人民是我国国民，为我国国民争取利好，就是爱国。
3、团结一切可以团结的人，放下思想冲突
发起群众斗群众是资本家的一大做法之一。
团结一切有两个方向，一是团结不同思想的人，比如毛左、马克思主义的无产阶级、西方神学思想中的人权、白左的人权思想等等，这些思想在指导方法上会有一些区别，比如毛左会认为中国人的事情就该中国人自己解决，马克思主义认为小资产阶级天生具有软弱性等等。但是没关系，放下思想冲突，只要是为了恢复八小时工作制和双休制的，一律支持。
二是团结不同群体的人，只要受劳动法保护的人群都应该尽可能团结。比如电子厂工人、医院的护士、合同制的国企政府外包员工，他们的共同点是在工作时间上不合理，而工作受劳动法保护。问题在于996icu群体和他们本身有着收入差距，他们可能带着一定的仇富心理看待996icu。所以996icu一部分内容可以加入提升最低工资，以拉拢更多的人。
**六、策略**
传播非常重要，一切行动都要有相对应的传播
1、对《劳动法》修改的研讨会和两会提案
如果有认识地方人大代表或者全国人大代表，可以起草一些两会提案，内容大致分为：一、加强监管部门（劳动保障监察部门）职能，严格监管执行劳动法执行情况；二、把劳动法的诉讼主体加入其他组织和竞争对手，使劳动法具有第三者可诉性。
对人大提案，一定要联系记者进行跟踪报道，让大众知晓。
2、要求信息公开《劳动保障监察条例》的执行状况
对自己省市的“劳动保障行政部门”进行信息公开，要求公开《劳动保障监察条例》第二章劳动保障监察职责第十一条第五项用人单位遵守工作时间和休息休假规定的情况。
一般来说，劳动监察大队是隶属于人力资源和社会保障局的事业单位，所以我们信息公开的对象是当地“人力资源和社会保障局”。
信息公开的内容（例）：1、劳动监察大队2018年工作报告。2、《劳动保障监察条例》第二章劳动保障监察职责第十一条第五项用人单位遵守工作时间和休息休假规定的情况。
信息公开是一个可诉行为，所以当信息公开之后，对信息公开的结果不满意是可以进行行政复议和行政诉讼的。现在很多政府机关对行政诉讼都有一定的指标，当地法院对行政诉讼的败诉率也有一定的压力。
故信息公开之后，一定要跟上相应的行政复议、行政诉讼、上诉，而且尽量联系媒体或自媒体进行多次的跟踪报道。
3、境外数次行为艺术和游行活动
在香港、台湾、美国纽约等人权理念发达国家地区进行游行和一些行为艺术，内容为抵制非人权产品和抛售非人权企业股票，给国内996工作制的企业制造经济压力。
游行和行为艺术的活动，主要目的是引起海内外群体和企业家关注，故要海内外媒体跟踪报道。
4、在各大论坛、自媒体宣扬八小时工作制双休制与革命英雄的关系
在今日头条、微信、微博、百家号等多个自媒体，以及百度贴吧等各类论坛（大家自己常逛的论坛就行），宣传无产阶级英雄革命家为争取双休制和八小时工作制的贡献，并争取把996和侮辱革命英雄挂钩。
5、建议把最低工资提升放入项目建设，以惠及更多人，当然这有利有弊。
6、注意保护信息安全
大家都是程序员我想这点不用多写。但是请务必注意TG群聊是不加密的，私聊默认也是不加密的，TG的聊天数据储存于服务器。如果合适的话，可以使用虚拟号码+signal的模式进行即时通讯。protonmail的邮件标题是不加密的，但是tutanota的邮件标题会进行加密。SS翻墙很方便，但是数据加密程度远不如openvpn。最后，钱的运转务必小心！

**Comment by CPdogson** [comment]
非常抱歉不得不使用一个全新的账号来发表言论，如果有需要的话我可以帮助完成一些立法建议的书写、信息公开申请书的书写、行政复议书和行政诉讼状的书写。非常希望能帮助到996icu这个项目。

我的邮箱是我的GitHub名字@protonmail.com，有合作意向可以直接向我发邮件。

**Comment by dushibeiying** [comment]
希望得到切实行动纲领的指引，真的很有必要。

**Comment by Tedko** [comment]
感谢建议！一起推动依法治国。

**Comment by firedom** [comment]
996问题从现在来看是怕被威胁或者由于一些个人原因担心公司将他开除所带来的风险（比如长时间没工作，被开除后可能没有别的公司愿意要自己）。这时选择继续工作加班虽然会很累，但是仍会给自己带来一定的安全感。

**Comment by Tedko** [comment]
协议里有写不得报复 可以看看@firedom

**Comment by kattgu7** [comment]
@CPdogson 感谢您的贡献！但是，这些内容是不是在996.LAW板块讨论比较好？我个人希望许可证暂时以学术研究项目的形式存在，谢谢！

**Comment by Tedko** [comment]
https://github.com/Y1ran/996.Law/issues/70

@CPdogson 劳动法这边，我转移到law那边去。
@firedom 协议的不得报复这块，咱们可以在协议兼容等其他issue里讨论。

**Comment by CPdogson** [comment]
有人要我证明我是我自己
UHRKGPF9B
非常希望能帮助到大家

**Comment by CPdogson** [comment]
UHRKGPF9B

**Comment by daiyeqi** [comment]
十分同意关于使用股市和贸易方式反抗996，那些996的公司其目的不就是上市么，上市前的审查大家可以去举报啊，公司违反劳动法不诚信啊。已经上市的公司让监管部门罚他款啊。

**Comment by CPdogson** [comment]
@kattgu7 @Tedko @firedom @dushibeiying @daiyeqi

非常感谢你们的支持，已转移到
https://github.com/CPdogson/996action
进行讨论和行动
