### ISSUE TITLE
我觉得许可证应该是copyleft的，像 GPL 那样

### ISSUE THREAD

**Issue by iamzhaohongxin** [kattgu7/Anti-996-License#21]
那样的话，能保证程序员的工作不被公司所占有，所有的代码属于开源社区

**Comment by ff4415** [comment]
许可证其实是个很复杂的法律问题。GPL只是其中一种，并不一定符合所有人的需求。 

- [an SPDX identifier](https://spdx.org/licenses/)
- [List of OSI approved licenses](https://opensource.org/licenses/alphabetical)
- [GNU's list of free licenses](https://www.gnu.org/licenses/license-list.en.html) (note: the license must be listed in one of the three "free" categories)
- [Open Definition's list of conformant licenses](https://opendefinition.org/licenses/) (non-code)

wiki百科相关的资料：

多协议共存: [multi-licensing](https://en.m.wikipedia.org/wiki/Multi-licensing)

协议兼容性: [License compatibility](https://en.m.wikipedia.org/wiki/License_compatibility)

**Comment by Tedko** [comment]
可以考虑 但是不想重复造轮子。

许可证法律比较复杂，不能一蹴而就。

**Comment by Tedko** [comment]
#10 
在这里讨论吧。GPL是一个好例子，但不一定要把他们的工作也做了。
