### ISSUE TITLE
是否应该扩大反996Licenced的模式与各行各业

### ISSUE THREAD

**Issue by KeaganWang** [kattgu7/Anti-996-License#28]
个人觉得基于其他license的方式可能会容易实现,但是目标群体太过集中于程序员身上,不仅仅程序员,我想现在这个社会上大多数人都在被资本主义蹂躏,这种情况下是否应该结合广大人民群众的力量,改变整个社会的加班风气,这样才是最根本的解决办法.仅仅依靠一个行业的发起是难以改变整个996式工作模式.就像当年的54运动一样,结合其他行业的人一起来抵抗这种不公平

**Comment by Tedko** [comment]
#12 在这里讨论吧

**Comment by Tedko** [comment]
谢谢
