### ISSUE TITLE
Anti-996 Presence in Wikimedia

### ISSUE THREAD

**Issue by rpfbl** [kattgu7/Anti-996-License#31]
Wikipedia（维基百科）是Wikimedia Foundation（维基媒体基金会）运营的在线百科全书项目，该组织同时运营着Wikinews、Wikisource、Wiktionary、Wikivoyage、Wikimedia Commons等多个项目，其中Wikimedia Commons是自由的多媒体资料库。昨日，996.ICU的标志被上传到Wikimedia Commons[1]，但在今天被某编者以标志使用了“非自由版权许可”为由提出了删除申请[2][3]。我想在此咨询法学博士Katt Gu @kattgu7 和您的丈夫Suji Yan @Tedko  ，如何才能可以在Wikimedia Commons当中保留该标志？

-----------
[1]: [File:996.ICU logo.png - Wikimedia Commons](https://commons.wikimedia.org/wiki/File:996.ICU_logo.png)
[2]: [关于996.ICU的非自由版权许可证](https://zh.wikipedia.org/wiki/Talk:996%E5%B7%A5%E4%BD%9C%E5%88%B6#%E5%85%B3%E4%BA%8E996.ICU%E7%9A%84%E9%9D%9E%E8%87%AA%E7%94%B1%E7%89%88%E6%9D%83%E8%AE%B8%E5%8F%AF%E8%AF%81)
[3]: [Commons:Deletion requests/File:996.ICU logo.png - Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:996.ICU_logo.png)

**Comment by rpfbl** [comment]
（第一次离大佬这么近，有点小紧张😄）

**Comment by Tedko** [comment]
谢谢 我们研究下

**Comment by ohhhhyaa** [comment]
https://zh.wikipedia.org/wiki/Anti-996-License

**Comment by ohhhhyaa** [comment]
https://zh.wikipedia.org/wiki/%E5%8F%8D_996_%E8%AE%B8%E5%8F%AF%E8%AF%81

**Comment by rpfbl** [comment]
@ohhhhyaa 被提出删除啦

**Comment by ohhhhyaa** [comment]
> @ohhhhyaa 被提出删除啦

是的 ，两条都被提出存废了

**Comment by ohhhhyaa** [comment]
> @ohhhhyaa 被提出删除啦

怎么会这样呢

**Comment by rpfbl** [comment]
> > @ohhhhyaa 被提出删除啦
> 
> 怎么会这样呢

因为这东西不适合放在那里

**Comment by ohhhhyaa** [comment]
> > > @ohhhhyaa 被提出删除啦
> > 
> > 
> > 怎么会这样呢
> 
> 因为这东西不适合放在那里

你补充下内容吖

**Comment by rpfbl** [comment]
@kattgu7

**Comment by Tedko** [comment]
996.icu的作者等需要在显著位置声明放弃版权？可能需要这样

**Comment by ff4415** [comment]
@Tedko 

可以展开说明一下吗？

**Comment by Tedko** [comment]
@ff4415 之前有一些人 写 (c) 20xx XXX, Inc 之类的吧。这样恐怕不行。

**Comment by Tedko** [comment]
我觉得reviewer只是担心图片版权问题

**Comment by ff4415** [comment]
@Tedko

几个关注点：

能把 Anti-996 license ，  MIT license 和 GPL license 之间的 继承 和 兼容 关系 展开说明一下吗。

**Comment by rpfbl** [comment]
@Tedko
经过查找，该图标的作者是Harry Liu（他是谁？他有GitHub账号吗？能找到他吗？）
在该图标被上传到996ICU repo的当时，还没有Anti 996 License。也就是说，比Anti 996 License早出现的图标要遵守后出现的Anti 996 License协议，这种情况该怎么办呢？

**Comment by rpfbl** [comment]
其实我也不是很确定作者是不是他，history里写的是“add logo.png committed by Harry Liu ⋅ 24af48c4”。

**Comment by ohhhhyaa** [comment]
支持

**Comment by Tedko** [comment]
> 其实我也不是很确定作者是不是他，history里写的是“add logo.png committed by Harry Liu ⋅ 24af48c4”。

那肯定在github上，找找他爸

**Comment by ohhhhyaa** [comment]
我找到了这个，你看看是不是加入logo的人https://github.com/ImgBotApp

**Comment by Tedko** [comment]
wiki上有讨论。可能需要授权给wiki基金会

**Comment by ohhhhyaa** [comment]
![QQ图片20190406102157](https://user-images.githubusercontent.com/49154848/55663803-e2ad8d80-5855-11e9-8892-40442be70ef0.png)

**Comment by ohhhhyaa** [comment]
![QQ图片20190406103658](https://user-images.githubusercontent.com/49154848/55663911-f823b700-5857-11e9-97e5-7a13489842d2.png)

**Comment by rpfbl** [comment]
> 我找到了这个，你看看是不是加入logo的人https://github.com/ImgBotApp

![IMG_20190406_113048](https://user-images.githubusercontent.com/41824047/55664393-76378c00-585f-11e9-8665-4e3eb49c5dab.jpg)
它是机器人啊hhhhhh

**Comment by rpfbl** [comment]
> > 其实我也不是很确定作者是不是他，history里写的是“add logo.png committed by Harry Liu ⋅ 24af48c4”。
> 
> 那肯定在github上，找找他吧

叫Harry Liu的一堆啊，每个profile page都看了，都不对。

**Comment by ohhhhyaa** [comment]
> > 我找到了这个，你看看是不是加入logo的人https://github.com/ImgBotApp
> 
> ![IMG_20190406_113048](https://user-images.githubusercontent.com/41824047/55664393-76378c00-585f-11e9-8665-4e3eb49c5dab.jpg)
> 它是机器人啊wwwwwwww

哈哈 我乌龙了

**Comment by xslidian** [comment]
最简单的方法是请原作者去 commons 上传。上传时的确认步骤就相当于授权（比 996 License 更宽松）。只要他不是被误导授权就行。

PR 是 @ser163 提交的，但 commit author 留了 163 邮箱，搜了关联 QQ 号应该是他本人。直接找原作者吧：
https://github.com/996icu/996.ICU/pull/16662

**Comment by Tedko** [comment]
请参考这一页 https://zh.wikipedia.org/wiki/%E5%8F%8D996%E8%AE%B8%E5%8F%AF%E8%AF%81

**Comment by Tedko** [comment]
> 请参考这一页 https://zh.wikipedia.org/wiki/%E5%8F%8D996%E8%AE%B8%E5%8F%AF%E8%AF%81

目前算是wiki通过了。大家可以讨论下多语言和更多细节（包括其他参与者，其他媒体等等）
