### ISSUE TITLE
想为996.icu做点事情

### ISSUE THREAD

**Issue by a289459798** [kattgu7/Anti-996-License#36]
看到appstore有一个996.icu的app，不确定是否为官方app
如果不是，我愿意无偿为996.icu开发
issues 被强制关闭，做一个线上的交流平台

**Comment by firedom** [comment]
想问下你有开发游戏软件的经验么？我想做一个996模拟器游戏但是不知道该从哪开始。

**Comment by Tedko** [comment]
> 看到appstore有一个996.icu的app，不确定是否为官方app
> 如果不是，我愿意无偿为996.icu开发
> issues 被强制关闭，做一个线上的交流平台

app不清楚，应该不是吧

**Comment by Tedko** [comment]
> 想问下你有开发游戏软件的经验么？我想做一个996模拟器游戏但是不知道该从哪开始。

你可以看看Galgame社区 BKE那个引擎

**Comment by rpfbl** [comment]
> 想问下你有开发游戏软件的经验么？我想做一个996模拟器游戏但是不知道该从哪开始。

https://github.com/kattgu7/Anti-996-License/issues/33
你不看issue吗？

**Comment by Tedko** [comment]
先关闭了。可以在其他issue讨论
