### ISSUE TITLE
How about changing the name to Ethical Software Development License?

### ISSUE THREAD

**Issue by kattgu7** [kattgu7/Anti-996-License#4]

**Comment by Tedko** [comment]
@firedom

**Comment by ff4415** [comment]
我认为 Ethical  这个词太温和，没有辨识度。 使用996icu或者996就挺好。有纪念性，有辨识度， 指向性强。

Personally,  I think the word Ethical is tender, has no identity.  
996icu or 996 is more impressive,  more aggressive, with monumentality and directionality.  
And it much easier to be remembered.  Surely it some kind harsh.

**Comment by firedom** [comment]
I'm not sure at the moment, but...

不建议中文许可证标题中出现劳工等字样，他的中文含义并不等同于英文含义。

虽然劳工与劳动者对应的英文都是Labor，但这个词在不同时代代表不同的含义。为了不使其产生歧义需要对其区分。

劳动者：为国家或者资本家或组织工作并取得合理的报酬，可以根据自己的意志决定自己的行为。
劳工：为国家或者资本家或组织义务工作，本身没有工资或相当于工资的补助仅够温饱。他的一切行为都听从统治者安排，本身没有话语权。

在解放前的中国或同时期的其它国家中，资本家、地主或者宗教势力（e.g. Tibet）会强迫穷人进行义务劳动。各种资源都集中于统治者手中，穷人有劳动的义务但不享有或仅享有让自己饿不死的劳动成果。

**Comment by kattgu7** [comment]
I have changed the name to Anti 996 license.

I agreed that ethical may be too broad. It may include situations like writing software for terrorist groups.

Let's just focus one labor protection at this moment.

**Comment by firedom** [comment]
道德与法律一样都有一个衡量标准，超过这个标准的人会被认为是道德高尚或者有较强的法律意识，低于这个标准的人会被认为是不讲究素质差或者法律意识淡薄。然而道德与法律的不同点是当一个人违反道德标准后除了被人谴责之外不会面其他临任何惩罚，而违反法律的后果却有可能面临自己无法承担的惩罚（没收财产、死刑等等）。所以如果许可证标题使用了Ethical或者其近义词会导致即使这个许可证的条款非常完善也依然没有任何约束效力。另外996这个词的限定范围过于狭隘，我们不希望看到某个组织发现这个许可证之后选择997工作制来回避规定（不过可以将996icu License作为别名对待）。

可以考虑这样的标题：
Reject Cruelty-Assignment License
Reject Abuse-working License

同时还应该把一些问题的决定权交给舆论解决，即使在这个过程中出现了一些大家都不希望出现的舆论观点[1][2][3]，但它可以激励更多的人参与进来并反对这个观点。如果在短时间内制定了一个绝对合理、让所有人挑不出问题的规定，虽然一样可以执行，但会让参与者养成将希望寄予他人而不是靠自己的力量去解决这个解决问题的习惯。

我还给一些项目发了请求添加996许可证的issues，我清楚这种类似骚扰的issues会让项目管理者感觉很不爽，不过我的这种做法不是要求项目管理者支持或反对这个许可证，而是通过这个过程让尽量多的人思考为什么会出现这种现象？我们接下来应该怎么做？

诚然制定996许可证可能是徒劳无意义的，但是制定过程反而起着比较重要的作用。在完善许可证的过程中可以让参与者思考并寻找其他更加有效的方式解决问题，因为它可能是接下来开展一系列行动的基础。

[1] https://www.v2ex.com/t/550550
[2] https://www.v2ex.com/t/550526
[3] https://www.zhihu.com/question/317920060

**Comment by ff4415** [comment]
@firedom 你唐突了。 会构成骚扰。
申请新license是有流程的。我开了个issue你看一下，按照流程走。
另外法律方面的事情还是交给专业人士来判断最好，我们保持最低要求的建议。务必一切从简。

**Comment by kattgu7** [comment]
@ff4415 @firedom 其实我自己也不知道写这个能达到什么样的效果，但我觉得就算不成功，这还是有象征意义的。
我个人觉得我们是不是可以联系一些媒体之类或者大V（twitter之类，weibo要被查水表估计）的报导？我知道有些媒体已经说过这个事情了，但这个也是个很好的后续报导。我和suji在和国外的一些twitter上比较知名的程序员接触，希望他们能够帮忙宣传一下这件事。我个人认为这种理念上的压迫的还是从国外打国内比较好。
