### ISSUE TITLE
Anti-996-License 应该有更多的传播渠道，如：微信公众平台，让更多的人知道它是干什么用的

### ISSUE THREAD

**Issue by githubmll** [kattgu7/Anti-996-License#41]

**Comment by kattgu7** [comment]
是有这个计划，但是现有版本还有很多地方要改……所以想再改一版本出来再想后续的事情。

**Comment by githubmll** [comment]
嗯嗯，后续有需要的话，我个人的微信公众号可以贡献出来，目前关注者比较乐观

**Comment by bingao** [comment]
这篇评论写得不错 https://user.guancha.cn/main/content?id=101520&comments-container
