### ISSUE TITLE
Is it possible to pull request including 996ICU license to the github official

### ISSUE THREAD

**Issue by ff4415** [kattgu7/Anti-996-License#5]
Shall we pull a request our License be added to the SPDX License List.

**Comment by ff4415** [comment]
[To Request Including License to choosealicense.com](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license)

[To Request a License or Exception Be Added to The SPDX License List](https://spdx.org/spdx-license-list/request-new-license)

**Comment by kattgu7** [comment]
@ff4415 It sounds great! But I have checked the requirement for adding the license and it looks like we have to satisfy several requirements. Should we start to approach projects who are willing to use the license?

Here is the requirement of Github:
Adding a license
Choosealicense.com is intended to demystify license choices, not present or catalog all of them. As such, only a small number are highlighted on the home page or https://choosealicense.com/licenses, and there are several requirements for a license to be cataloged on the site:

The license must have an SPDX identifier. If your license isn't registered with SPDX, please request that it be added.
The license must be listed on one of the following approved lists of licenses:
List of OSI approved licenses
GNU's list of free licenses (note: the license must be listed in one of the three "free" categories)
Open Definition's list of conformant licenses (non-code)
A GitHub code search must reveal at least 1,000 public repositories using the license.
3 notable projects using the license must be identified. These must have straightforward LICENSE files which serve as examples newcomers can follow and that could be detected by licensee if it knew about the license.

**Comment by ff4415** [comment]
@kattgu7  Yes, it said that we must pull request 996ICU License be added to the SPDX License List first. 
Here is the url:
https://spdx.org/spdx-license-list/request-new-license

**Comment by ff4415** [comment]
@kattgu7 Oops, I get what U meaning.

**Comment by Tedko** [comment]
yeah let me try.

**Comment by ff4415** [comment]
After all there is still a good news that we already have one notable project using this license. ~_~
