### ISSUE TITLE
@ff4415 @firedom 其实我自己也不知道写这个能达到什么样的效果，但我觉得就算不成功，这还是有象征意义的。

### ISSUE THREAD

**Issue by firedom** [kattgu7/Anti-996-License#6]
@ff4415 @firedom 其实我自己也不知道写这个能达到什么样的效果，但我觉得就算不成功，这还是有象征意义的。
我个人觉得我们是不是可以联系一些媒体之类或者大V（twitter之类，weibo要被查水表估计）的报导？我知道有些媒体已经说过这个事情了，但这个也是个很好的后续报导。我和suji在和国外的一些twitter上比较知名的程序员接触，希望他们能够帮忙宣传一下这件事。我个人认为这种理念上的压迫的还是从国外打国内比较好。

_Originally posted by @kattgu7 in https://github.com/kattgu7/996-License-Draft/issues/4#issuecomment-478437556_

我看到国内的一些组织认为外国政府（U.S. mostly）会以中国发展太快为由进行资源封锁，但是国内一些组织应该想不到还可以以Anti996的方式达到同样的目的。

**Comment by kattgu7** [comment]
@firedom 可以想想从国外的哪些方面入手好。

**Comment by ff4415** [comment]
@kattgu7  

其实只要996ICU license 被 GitHub 官方收录就可以算是成功了。  
就现在来说影响已经很大了。 全站 stars 数量第二。 

排名第一的项目代表了自由软件运动的最高原则:  分享 。 然后第二的就是996ICU。
它代表什么我一下子说不清，我想它代表很多。

 如果你能联系到知名的程序员一起推动 996ICU license 进入 GitHub 的 licenses 选择列表，那么这次事件的影响就不会随着热度消散而消失。

以后每有程序员建立新 repo 的时候，就会想起现在发生的事情。 当使用 996ICU license 的项目足够多足够健壮的时候，世界就不一样了。

千万不要和政治扯上任何关系。 那是饮鸩止渴。 
我被知乎短期禁言了。 不过相关的讨论并没有禁止。
京东作为众矢之的，状况也不好。 高管离职，环比增长率降到 4% ， 大量员工离职。

我认为现在事情的热度已经达到官方忍耐的临界了。

所以我认为，只要 GitHub 高亮了 996ICU license。  事情以技术的方式开始，然后以技术的方式结束。在GitHub开始，由GitHub结束。没有比这更完美了。

你可以 了解一下 [GNU](https://www.gnu.org/gnu/gnu.html) 自由软件运动。 
这应该也是GitHub坚持的原则。

我认为我们现在所做的事情是继承了GNU的理念的。只不过反对的事物，从美国，转移到了中国。
但是精神还是一样的。

所以我认为得到GitHub的承认很重要。

**Comment by bofeiw** [comment]
支持你们！加油！

**Comment by firedom** [comment]
我同意目前不要和政治扯上关系，因为我看到了一些言论认为要彻底解决问题需要推翻并重建政权。我承认他们的想法很朴素，但同样也有这样做了以后反而让问题更严重的例子，并且还会出现事情的发展违背初衷的情况。

**Comment by firedom** [comment]
> @kattgu7
> 
> 其实只要996ICU license 被 GitHub 官方收录就可以算是成功了。
> 就现在来说影响已经很大了。 全站 stars 数量第二。
> 
> 排名第一的项目代表了自由软件运动的最高原则: 分享 。 然后第二的就是996ICU。
> 它代表什么我一下子说不清，我想它代表很多。
> 
> 如果你能联系到知名的程序员一起推动 996ICU license 进入 GitHub 的 licenses 选择列表，那么这次事件的影响就不会随着热度消散而消失。
> 
> 以后每有程序员建立新 repo 的时候，就会想起现在发生的事情。 当使用 996ICU license 的项目足够多足够健壮的时候，世界就不一样了。
> 
> 千万不要和政治扯上任何关系。 那是饮鸩止渴。
> 我被知乎短期禁言了。 不过相关的讨论并没有禁止。
> 京东作为众矢之的，状况也不好。 高管离职，环比增长率降到 4% ， 大量员工离职。
> 
> 我认为现在事情的热度已经达到官方忍耐的临界了。
> 
> 所以我认为，只要 GitHub 高亮了 996ICU license。 事情以技术的方式开始，然后以技术的方式结束。在GitHub开始，由GitHub结束。没有比这更完美了。
> 
> 你可以 了解一下 [GNU](https://www.gnu.org/gnu/gnu.html) 自由软件运动。
> 这应该也是GitHub坚持的原则。
> 
> 我认为我们现在所做的事情是继承了GNU的理念的。只不过反对的事物，从美国，转移到了中国。
> 但是精神还是一样的。
> 
> 所以我认为得到GitHub的承认很重要。

尽最大努力宣传/充分发动群众力量的好处就是个人的禁言（牺牲）不会影响事件整体发展进程，反而会让大家将你视为Hero。

**Comment by kattgu7** [comment]
@firedom 我翻译过一本关于自由软件运动的书，所以还是了解一些。
现在还有人提出来要兼容其他license，我觉得这个主意很好。我没见过其他允许兼容的怎么写，如果有资料的话可以发给我参考一下。

**Comment by firedom** [comment]
> @firedom 可以想想从国外的哪些方面入手好。

从最理想的角度看需要让各种标准定义组织(IEEE, W3C, IETF, ISO/IEC, 3GPP and etc)和编程语言标准制定组织(C/C++, Go, Python, Rust, PHP and etc)等接受Anti996 License。因为从某种程度上来说，包括编程语言以及Nginx, MariaDB在内的各种项目所做的只是将这些标准用代码实现而已，如果开发者在使用这些标准或工具编写代码时被迫以不人道的方式进行工作，那么这些组织就可以不承认他所做的项目。

不过这种方法面前是不可行的因为996ICU的影响力还不够。目前比较合理的方法是先呼吁现有的开发者将Anti996 License加入到自己的项目中，不论自己的项目是否有人使用，同时我会试图向一些比较有影响力的项目发请求添加许可证issues，让项目管理者对这件事有一定的了解（虽然被close的可能性较大），用这种方式让更多人知道这件事。

目前我手里关于GNU运动的资料不是很多，我可能会先找一下资料再决定应该怎么做才更合适。

**Comment by ff4415** [comment]
### [EmpathDB/LICENSE](https://github.com/goldnuggets24/EmpathDB/blob/7a6c61a9363d957276af50292fd362796055cedc/LICENSE)

> Copyright (c) 2015, diowa
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this
>    list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice,
>    this list of conditions and the following disclaimer in the documentation
>    and/or other materials provided with the distribution.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
> ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
> WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
> DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
> ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
> (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
> LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
> ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
> SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> 
> airbrake is licensed by Airbrake
> 
> Autoprefixer Rails is licensed under the MIT License
> 
> better_errors is licensed under the MIT License
> 
> binding_of_caller is licensed under the MIT License
> 
> bullet is licensed under the MIT License
> 
> byebug is licensed under the MIT License
> 
> Bootstrap for Sass is licensed under the MIT License
> 
> Capybara is licensed under the MIT License
> 
> Database Cleaner is licensed under the MIT License
> 
> Email Spec is licensed under the MIT License
> 
> factory_girl_rails is licensed under the MIT License
> 
> faker is licensed under the MIT License
> 
> figaro is licensed under the MIT License
> 
> FontAwesome font is licensed under the SIL Open Font License
> 
> FontAwesome is licensed under the MIT License
> 
> FontAwesome pictograms are licensed under the CC BY 3.0 License
> 
> google-analytics-rails is licensed under the MIT license
> 
> http_accept_language is licensed under the MIT License
> 
> i18n-js is licensed under the MIT License
> 
> jquery is licensed under the MIT License
> 
> jquery-turbolinks is licensed under the MIT License
> 
> kaminari is licensed under the MIT License
> 
> meta_request is licensed under the MIT License
> 
> newrelic_rpm is licensed by New Relic
> 
> nokogiri is licensed under the MIT License
> 
> pg is licensed under the 2-clause BSD License
> 
> pry is licensed under the MIT License
> 
> pry-byebug is licensed under the MIT License
> 
> pry-rails is licensed under the MIT License
> 
> puma is licensed under the BSD License
> 
> puma_auto_tune is licensed under the MIT License
> 
> rabl is licensed under the MIT License
> 
> Rack::Timeout is licensed under the MIT License
> 
> rails_12factor is licensed under the 2-clause BSD License
> 
> resque is licensed under the MIT License
> 
> rest-client is licensed under the MIT License
> 
> rspec is licensed under the MIT License
> 
> rspec-rails is licensed under the MIT License
> 
> secure_headers is licensed under the Apache License
> 
> selenium-webdriver is licensed under the Apache License
> 
> simplecov is licensed under the MIT License
> 
> slim-rails is licensed under the MIT License
> 
> spring_commands_rspec is licensed under the MIT License
> 
> twbs_sass_rails is licensed under the 2-clause BSD License
> 
> uglifier is licensed under the MIT License
> 
> validates_timeliness is licensed under the MIT License
> 
> webmock is licensed under the MIT License

**Comment by firedom** [comment]
（次要问题）将这个许可证进行延伸的话也同样可以约束用自己身体健康（不吃饭、不运动、天天不睡觉等）换取工作效率的个人开发者，我们不欢迎社区中存在这样的项目。

**Comment by ff4415** [comment]
> > @firedom 可以想想从国外的哪些方面入手好。
> 
> 从最理想的角度看需要让各种标准定义组织(IEEE, W3C, IETF, ISO/IEC, 3GPP and etc)和编程语言标准制定组织(C/C++, Go, Python, Rust, PHP and etc)等接受Anti996 License。因为从某种程度上来说，包括编程语言以及Nginx, MariaDB在内的各种项目所做的只是将这些标准用代码实现而已，如果开发者在使用这些标准或工具编写代码时被迫以不人道的方式进行工作，那么这些组织就可以不承认他所做的项目。
> 
> 不过这种方法面前是不可行的因为996ICU的影响力还不够。目前比较合理的方法是先呼吁现有的开发者将Anti996 License加入到自己的项目中，不论自己的项目是否有人使用，同时我会试图向一些比较有影响力的项目发请求添加许可证issues，让项目管理者对这件事有一定的了解（虽然被close的可能性较大），用这种方式让更多人知道这件事。
> 
> 目前我手里关于GNU运动的资料不是很多，我可能会先找一下资料再决定应该怎么做才更合适。

----

这个是不可能的。
能争取的只有MIT协议下面的项目。

像C++， GO，这样的都是有主的。

**Comment by ff4415** [comment]
### [996.ICU/externals/instruction.md](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md)

#### License file
The 996ICU license is designed for multi-licensing, you can use it with other licenses like MIT in these ways:
- Separate license files:
  - In `LICENSE` file, list all licenses you used with `AND`.
  - Add `LICENSE.996ICU` or `LICENSE.NPL` file for details of 996ICU license.
  - Add `LICENSE.MIT` file for details of MIT license.
- Single license files:
  - Add primary license content, such as MIT license.
  - Add separation line like `----------`.
  - Add 996ICU license content.

**Comment by ff4415** [comment]
[multi-licensing](https://en.m.wikipedia.org/wiki/Multi-licensing)

[License compatibility](https://en.m.wikipedia.org/wiki/License_compatibility)

**Comment by dear-Alice-moon** [comment]
> @kattgu7
> 
> 其实只要996ICU license 被 GitHub 官方收录就可以算是成功了。
> 就现在来说影响已经很大了。 全站 stars 数量第二。
> 
> 排名第一的项目代表了自由软件运动的最高原则: 分享 。 然后第二的就是996ICU。
> 它代表什么我一下子说不清，我想它代表很多。
> 
> 如果你能联系到知名的程序员一起推动 996ICU license 进入 GitHub 的 licenses 选择列表，那么这次事件的影响就不会随着热度消散而消失。
> 
> 以后每有程序员建立新 repo 的时候，就会想起现在发生的事情。 当使用 996ICU license 的项目足够多足够健壮的时候，世界就不一样了。
> 
> 千万不要和政治扯上任何关系。 那是饮鸩止渴。
> 我被知乎短期禁言了。 不过相关的讨论并没有禁止。
> 京东作为众矢之的，状况也不好。 高管离职，环比增长率降到 4% ， 大量员工离职。
> 
> 我认为现在事情的热度已经达到官方忍耐的临界了。
> 
> 所以我认为，只要 GitHub 高亮了 996ICU license。 事情以技术的方式开始，然后以技术的方式结束。在GitHub开始，由GitHub结束。没有比这更完美了。
> 
> 你可以 了解一下 [GNU](https://www.gnu.org/gnu/gnu.html) 自由软件运动。
> 这应该也是GitHub坚持的原则。
> 
> 我认为我们现在所做的事情是继承了GNU的理念的。只不过反对的事物，从美国，转移到了中国。
> 但是精神还是一样的。
> 
> 所以我认为得到GitHub的承认很重要。

我感觉你讲的真好，我前来留言，支持你一下。

**Comment by kattgu7** [comment]
我close一下这个issue，待会儿开两个新的大家来讨论compatibility和申请github官方认证的问题
