### ISSUE TITLE
是否可以设计成附加协议，如主协议是Apache License 2.0，附加本协议

### ISSUE THREAD

**Issue by terrynoya** [kattgu7/Anti-996-License#7]
如题，作为附加协议，这样可以在不变更主协议（如Apache License 2.0）的情况下，附加本协议，这样可以获得现有的大型开源项目的支持。

**Comment by Tedko** [comment]
可以。准备做一些范例之后

**Comment by kattgu7** [comment]
@terrynoya 可以，在研究有没有其他附加协议的范本。

**Comment by kattgu7** [comment]
@terrynoya 你看到过有的话能不能给我发一下？

**Comment by ff4415** [comment]
@terrynoya

是这个吗？

[gen-license](https://github.com/996icu/996.ICU/tree/master/archived/licenses%5BWIP%5D/tools/gen-license)

Generate LICENSES. Use Python3.

All LICENSE file comes from github. to see the license code here

Support 996.ICU Expanded LICENSE

Install
    # after git clone or other download way.
    cd gen-license && python setup.py install
    # or
    cd gen-license && python setup.py install --user
Usage
    # Common LICENSE
    gen-license mit # generate mit LICENSE file in current directory

    # List LICENSE codes
    gen-license --list

    # Conmmon LICENSE with 996ICU
    gen-license mit --996icu # generate mit LICENSE with 996ICU zh-cn version
    gen-license mit --996icu en-us # generate mit LICENSE with 996ICU en-us version

**Comment by ff4415** [comment]
看看这个


### [EmpathDB/LICENSE](https://github.com/goldnuggets24/EmpathDB/blob/7a6c61a9363d957276af50292fd362796055cedc/LICENSE)

> Copyright (c) 2015, diowa
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this
>    list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice,
>    this list of conditions and the following disclaimer in the documentation
>    and/or other materials provided with the distribution.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
> ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
> WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
> DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
> ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
> (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
> LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
> ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
> SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> 
> airbrake is licensed by Airbrake
> 
> Autoprefixer Rails is licensed under the MIT License
> 
> better_errors is licensed under the MIT License
> 
> binding_of_caller is licensed under the MIT License
> 
> bullet is licensed under the MIT License
> 
> byebug is licensed under the MIT License
> 
> Bootstrap for Sass is licensed under the MIT License
> 
> Capybara is licensed under the MIT License
> 
> Database Cleaner is licensed under the MIT License
> 
> Email Spec is licensed under the MIT License
> 
> factory_girl_rails is licensed under the MIT License
> 
> faker is licensed under the MIT License
> 
> figaro is licensed under the MIT License
> 
> FontAwesome font is licensed under the SIL Open Font License
> 
> FontAwesome is licensed under the MIT License
> 
> FontAwesome pictograms are licensed under the CC BY 3.0 License
> 
> google-analytics-rails is licensed under the MIT license
> 
> http_accept_language is licensed under the MIT License
> 
> i18n-js is licensed under the MIT License
> 
> jquery is licensed under the MIT License
> 
> jquery-turbolinks is licensed under the MIT License
> 
> kaminari is licensed under the MIT License
> 
> meta_request is licensed under the MIT License
> 
> newrelic_rpm is licensed by New Relic
> 
> nokogiri is licensed under the MIT License
> 
> pg is licensed under the 2-clause BSD License
> 
> pry is licensed under the MIT License
> 
> pry-byebug is licensed under the MIT License
> 
> pry-rails is licensed under the MIT License
> 
> puma is licensed under the BSD License
> 
> puma_auto_tune is licensed under the MIT License
> 
> rabl is licensed under the MIT License
> 
> Rack::Timeout is licensed under the MIT License
> 
> rails_12factor is licensed under the 2-clause BSD License
> 
> resque is licensed under the MIT License
> 
> rest-client is licensed under the MIT License
> 
> rspec is licensed under the MIT License
> 
> rspec-rails is licensed under the MIT License
> 
> secure_headers is licensed under the Apache License
> 
> selenium-webdriver is licensed under the Apache License
> 
> simplecov is licensed under the MIT License
> 
> slim-rails is licensed under the MIT License
> 
> spring_commands_rspec is licensed under the MIT License
> 
> twbs_sass_rails is licensed under the 2-clause BSD License
> 
> uglifier is licensed under the MIT License
> 
> validates_timeliness is licensed under the MIT License
> 
> webmock is licensed under the MIT License

**Comment by sinri** [comment]
I wonder if it is possible (and legal anyway) to append a special condition to an existed license such as GPLv3, such as [this draft](https://github.com/sinri/Alderamin/blob/master/LICENSE).

**Comment by ff4415** [comment]
@sinri

### [996.ICU/externals/instruction.md](https://github.com/996icu/996.ICU/blob/master/externals/instruction.md)

#### License file
The 996ICU license is designed for multi-licensing, you can use it with other licenses like MIT in these ways:
- Separate license files:
  - In `LICENSE` file, list all licenses you used with `AND`.
  - Add `LICENSE.996ICU` or `LICENSE.NPL` file for details of 996ICU license.
  - Add `LICENSE.MIT` file for details of MIT license.
- Single license files:
  - Add primary license content, such as MIT license.
  - Add separation line like `----------`.
  - Add 996ICU license content.

**Comment by sinri** [comment]
@ff4415 
Emmm, single license file used, seems ok with some modification.
