### ISSUE TITLE
Target to be available in SPDX

### ISSUE THREAD

**Issue by sinri** [kattgu7/Anti-996-License#8]
There might be a target to list this license to

https://spdx.org/licenses/

**Comment by sinri** [comment]
Found it is declared in 

https://github.com/996icu/996.ICU/blob/master/proposal/proposal_To_Request_Github_Official_Including_996ICU_License.md

**Comment by kattgu7** [comment]
@sinri Thanks!

**Comment by kattgu7** [comment]
@sinri we are working on this right now.

**Comment by sinri** [comment]
Thanks @kattgu7
